=== pixel-ports/pas_modelling/data_models/Parameters/temp.SUPPLY-CHAINS_schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",

  "$id": "supply_chains_list",
  "type": "array",
  "description": "The collection of Supply-chain description.",
  "items": {
    "$id": "#/items",
    "type": "object",
    "description": "A supply-chain description.",
    "required": [
      "ID",
      "steps_list"
    ],
    "properties": {
      "ID": {
        "$id": "#/items/properties/ID",
        "type": "string",
        "description": "Unique identifier.",
        "examples": [
          "SC_1"
        ]
      },
      "label": {
        "$id": "#/items/properties/label",
        "type": "string",
        "description": "Free text for labelling (eg. name).",
        "examples": [
          "My SC name"
        ]
      },
      "comment": {
        "$id": "#/items/properties/comment",
        "type": "string",
        "description": "Free text for comment",
        "examples": [
          "Some SC comment"
        ]
      },
      "compatibility": {
        "$id": "#/items/properties/compatibility",
        "type": "object",
        "description": "Informations about suitable handling context.",
        "required": [
        ],
        "properties": {
          "cargoes_category": {
            "$id": "#/items/properties/compatibility/properties/cargoes_category",
            "type": "array",
            "description": "List of compatible handlings' cargoes-categories.",
            "items": {
              "$id": "#/items/properties/compatibility/properties/cargoes_category/items",
              "type": "string",
              "description": "Valid cargo-category's ID.",
              "examples": [
                "E.Mais Vrac"
              ]
            }
          },
          "directions_nature": {
            "$id": "#/items/properties/compatibility/properties/directions_nature",
            "type": "array",
            "description": "List compatible handlings' directions.",
            "items": {
              "$id": "#/items/properties/compatibility/properties/directions_nature/items",
              "type": "string",
              "description": "A direction.",
              "enum": ["loading", "unloading", "other"],
              "examples": [
                "loading"
              ]
            }
          },
          "areas_ID": {
            "$id": "#/items/properties/compatibility/properties/areas_ID",
            "type": "array",
            "description": "List compatible handlings' areas.",
            "items": {
              "$id": "#/items/properties/compatibility/properties/areas_ID/items",
              "type": "string",
              "description": "Valid area's ID.",
              "examples": [
                "419",
                "432",
                "Silo_SPBL"
              ]
            }
          },
          "shiftworks_ID": {
            "$id": "#/items/properties/compatibility/properties/shiftworks_ID",
            "type": "array",
            "description": "List compatible handlings' work hours.",
            "items": {
              "$id": "#/items/properties/compatibility/properties/shiftworks_ID/items",
              "type": "string",
              "description": "Valid shiftwork's ID.",
              "examples": [
                "typical"
              ]
            }
          }
        }
      },
      "steps_list": {
        "$id": "#/items/properties/steps_list",
        "type": "array",
        "description": "An explanation about the purpose of this instance.",
        "items": {
          "$id": "#/items/properties/steps_list/items",
          "type": "object",
          "description": "An explanation about the purpose of this instance.",
          "minProperties": 0,
          "required": [
            "ID",
            "label",
            "comment",
            "category",
            "scheduling",
            "work"
          ],
          "properties": {
            "ID": {
              "$id": "#/items/properties/steps_list/items/properties/ID",
              "type": "string",
              "description": "An explanation about the purpose of this instance.",
              "examples": [
                "step_1"
              ]
            },
            "label": {
              "$id": "#/items/properties/steps_list/items/properties/label",
              "type": "string",
              "description": "An explanation about the purpose of this instance.",
              "examples": [
                "Allumage de la centrale hydraulique"
              ]
            },
            "comment": {
              "$id": "#/items/properties/steps_list/items/properties/comment",
              "type": "string",
              "description": "An explanation about the purpose of this instance.",
              "examples": [
                "Premier allumage"
              ]
            },
            "category": {
              "$id": "#/items/properties/steps_list/items/properties/category",
              "type": "string",
              "description": "An explanation about the purpose of this instance.",
              "examples": [
                "Initialization '<<examples':['Initialization', 'Processing', 'Support', '<<Discontinuous'],"
              ]
            },
            "scheduling": {
              "$id": "#/items/properties/steps_list/items/properties/scheduling",
              "type": "object",
              "description": "An explanation about the purpose of this instance.",
              "minProperties": 0,
              "required": [
                "start",
                "duration"
              ],
              "properties": {
                "start": {
                  "$id": "#/items/properties/steps_list/items/properties/scheduling/properties/start",
                  "type": "object",
                  "description": "An explanation about the purpose of this instance.",
                  "minProperties": 0,
                  "required": [
                    "nature",
                    "value"
                  ],
                  "properties": {
                    "nature": {
                      "$id": "#/items/properties/steps_list/items/properties/scheduling/properties/start/properties/nature",
                      "type": "string",
                      "description": "An explanation about the purpose of this instance.",
                      "examples": [
                        "delay '<<enum':['delay', 'with_any', 'with_all', 'after_any', 'after_all'], <<comment':'For 'delay': the number of hours (number). For others than 'delay': all the steps's ID to which the condition relates (array).'"
                      ]
                    },
                    "value": {
                      "$id": "#/items/properties/steps_list/items/properties/scheduling/properties/start/properties/value",
                      "type": "integer",
                      "description": "An explanation about the purpose of this instance.",
                      "examples": [
                        0
                      ]
                    }
                  }
                },
                "duration": {
                  "$id": "#/items/properties/steps_list/items/properties/scheduling/properties/duration",
                  "type": "object",
                  "description": "An explanation about the purpose of this instance.",
                  "minProperties": 0,
                  "required": [
                    "nature",
                    "value"
                  ],
                  "properties": {
                    "nature": {
                      "$id": "#/items/properties/steps_list/items/properties/scheduling/properties/duration/properties/nature",
                      "type": "string",
                      "description": "An explanation about the purpose of this instance.",
                      "examples": [
                        "whith_any <<enum':['delay', 'cargo_tons', 'cargo_%', 'with_any', 'with_all', 'after_any', 'after_all'] <<For 'cargo_amount': the amount and unit (can be tons or percent). For others than 'cargo_amount': see start>value's comment."
                      ]
                    },
                    "value": {
                      "$id": "#/items/properties/steps_list/items/properties/scheduling/properties/duration/properties/value",
                      "type": "array",
                      "description": "An explanation about the purpose of this instance.",
                      "items": {
                        "$id": "#/items/properties/steps_list/items/properties/scheduling/properties/duration/properties/value/items",
                        "type": "string",
                        "description": "An explanation about the purpose of this instance.",
                        "examples": [
                          "step_3",
                          "step_4"
                        ]
                      }
                    }
                  }
                }
              }
            },
            "work": {
              "$id": "#/items/properties/steps_list/items/properties/work",
              "type": "object",
              "description": "An explanation about the purpose of this instance.",
              "minProperties": 0,
              "required": [
                "machines",
                "nature",
                "distance"
              ],
              "properties": {
                "machines": {
                  "$id": "#/items/properties/steps_list/items/properties/work/properties/machines",
                  "type": "array",
                  "description": "An explanation about the purpose of this instance.",
                  "items": {
                    "$id": "#/items/properties/steps_list/items/properties/work/properties/machines/items",
                    "type": "string",
                    "description": "An explanation about the purpose of this instance.",
                    "examples": [
                      "machine_1 <<Every listed machines start and stop together. If not, use separate step"
                    ]
                  }
                },
                "nature": {
                  "$id": "#/items/properties/steps_list/items/properties/work/properties/nature",
                  "type": "string",
                  "description": "An explanation about the purpose of this instance.",
                  "examples": [
                    "parallel'<<enum':['parallel', 'sequential'],"
                  ]
                },
                "distance": {
                  "$id": "#/items/properties/steps_list/items/properties/work/properties/distance",
                  "type": "string",
                  "description": "An explanation about the purpose of this instance.",
                  "examples": [
                    "on_spot <<'on_spot' for static machines use, number of m for moving machine (impacting throughput calculation)"
                  ]
                }
              }
            }
          }
        }
      }
    }
  }
}

=== pixel-ports/pas_modelling/data_models/Parameters/temp.SUPPLY-CHAINS_example.json
[
	{
		"ID":"SC_1",
		"label":"Cereale_SPBL_Export",
		"comment":"Se d√©compose en trois blocs : initialisation (du portique et temps mort tapis), acheminement et ajustement du portique.",
		"compatibility":{
			"cargoes_category":["E.Mais Vrac"],
			"directions_nature":["loading"],
			"areas_ID":["419", "432", "Silo_SPBL"],
			"shiftworks_ID":["typical"]
		},
		"steps_list":[
			{
				"ID":"step_1",
				"label":"Allumage de la centrale hydraulique",
				"comment":"Premier allumage",
				"category":"Initialization '<<examples':['Initialization', 'Processing', 'Support', '<<Discontinuous'],",
				"scheduling":{
					"start":{
						"nature":"delay '<<enum':['delay', 'with_any', 'with_all', 'after_any', 'after_all'], <<comment':'For 'delay': the number of hours (number). For others than 'delay': all the steps's ID to which the condition relates (array).'",
						"value":0
					},
					"duration":{
						"nature":"whith_any <<enum':['delay', 'cargo_tons', 'cargo_%', 'with_any', 'with_all', 'after_any', 'after_all'] <<For 'cargo_amount': the amount and unit (can be tons or percent). For others than 'cargo_amount': see start>value's comment.",
						"value":["step_3", "step_4"]
					}
				},
				"work":{
					"machines":["machine_1 <<Every listed machines start and stop together. If not, use separate step"],
					"nature":"parallel'<<enum':['parallel', 'sequential'],",
					"distance":"on_spot <<'on_spot' for static machines use, number of m for moving machine (impacting throughput calculation)"
				}
			}
		]
	}
]
